import type { JokerDef } from '../types'

export const JOKER_DEFS: JokerDef[] = [
  {
    id: 'joker',
    name: 'joker',
    description: '+4 mult',
    rarity: 'common',
    cost: 2,
    trigger: 'on_score',
    condition: { type: 'always' },
    effect: { type: 'add_mult', amount: 4 },
  },
  {
    id: 'greedy-joker',
    name: 'greedy joker',
    description: '+3 mult if played hand contains a diamond',
    rarity: 'common',
    cost: 5,
    trigger: 'on_score',
    condition: { type: 'contains_suit', suit: 'diamonds' },
    effect: { type: 'add_mult', amount: 3 },
  },
  {
    id: 'lusty-joker',
    name: 'lusty joker',
    description: '+3 mult if played hand contains a heart',
    rarity: 'common',
    cost: 5,
    trigger: 'on_score',
    condition: { type: 'contains_suit', suit: 'hearts' },
    effect: { type: 'add_mult', amount: 3 },
  },
  {
    id: 'wrathful-joker',
    name: 'wrathful joker',
    description: '+3 mult if played hand contains a spade',
    rarity: 'common',
    cost: 5,
    trigger: 'on_score',
    condition: { type: 'contains_suit', suit: 'spades' },
    effect: { type: 'add_mult', amount: 3 },
  },
  {
    id: 'glutton-joker',
    name: 'glutton joker',
    description: '+3 mult if played hand contains a club',
    rarity: 'common',
    cost: 5,
    trigger: 'on_score',
    condition: { type: 'contains_suit', suit: 'clubs' },
    effect: { type: 'add_mult', amount: 3 },
  },
  {
    id: 'jolly-joker',
    name: 'jolly joker',
    description: '+8 mult if played hand contains a pair',
    rarity: 'common',
    cost: 3,
    trigger: 'on_score',
    condition: { type: 'hand_type_is', handType: 'pair' },
    effect: { type: 'add_mult', amount: 8 },
  },
  {
    id: 'zany-joker',
    name: 'zany joker',
    description: '+12 mult if played hand contains a three of a kind',
    rarity: 'common',
    cost: 4,
    trigger: 'on_score',
    condition: { type: 'hand_type_is', handType: 'three_of_a_kind' },
    effect: { type: 'add_mult', amount: 12 },
  },
  {
    id: 'mad-joker',
    name: 'mad joker',
    description: '+10 mult if played hand contains a two pair',
    rarity: 'common',
    cost: 4,
    trigger: 'on_score',
    condition: { type: 'hand_type_is', handType: 'two_pair' },
    effect: { type: 'add_mult', amount: 10 },
  },
  {
    id: 'crazy-joker',
    name: 'crazy joker',
    description: '+12 mult if played hand contains a straight',
    rarity: 'uncommon',
    cost: 4,
    trigger: 'on_score',
    condition: { type: 'hand_type_is', handType: 'straight' },
    effect: { type: 'add_mult', amount: 12 },
  },
  {
    id: 'sly-joker',
    name: 'sly joker',
    description: '+50 chips if played hand contains a pair',
    rarity: 'common',
    cost: 3,
    trigger: 'on_score',
    condition: { type: 'hand_type_is', handType: 'pair' },
    effect: { type: 'add_chips', amount: 50 },
  },
  {
    id: 'half-joker',
    name: 'half joker',
    description: '+20 mult if played hand has 3 or fewer cards',
    rarity: 'common',
    cost: 5,
    trigger: 'on_score',
    condition: { type: 'played_count_lte', count: 3 },
    effect: { type: 'add_mult', amount: 20 },
  },
  {
    id: 'steel-joker',
    name: 'steel joker',
    description: '×1.5 mult',
    rarity: 'uncommon',
    cost: 7,
    trigger: 'on_score',
    condition: { type: 'always' },
    effect: { type: 'mul_mult', factor: 1.5 },
  },
]

export function getJokerDef(id: string): JokerDef | undefined {
  return JOKER_DEFS.find((j) => j.id === id)
}
